Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -28,20 +28,22 @@ jobs:
 
       - name: List all changed files
         run: |
+          IFS=$',' GLOBIGNORE='*' command eval  'ignore=($(cat .github/workflows/ignore.txt))'
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do  
             readarray -d , -t arr < .github/workflows/check_for.txt
-            IFS=$',' GLOBIGNORE='*' command eval  'ignore=($(cat .github/workflows/ignore.txt))'
             fail_it="false"
             for i in "${arr[@]}"
-            do
-              if [[ " ${ignore[*]} " =~ " ${i} " ]]; then
+            if [[ " ${ignore[*]} " =~ " ${file} " ]]; then
                 echo "$file is ignored"
-              elif grep -q $i "$file"; then
-                echo "$file has $i fail it"
-                fail_it="true"
+            else
+              do
+                if grep -q $i "$file"; then
+                  echo "$file has $i fail it"
+                  fail_it="true"
+                fi
+              done
+              if [ $fail_it == "true" ]; then
+                exit 1
               fi
-            done
-            if [ $fail_it == "true" ]; then
-              exit 1
             fi
           done
