Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -28,23 +28,24 @@ jobs:
 
       - name: List all changed files
         run: |
-          ignore = ("test.xml");
-          echo "$ignore"
+          declare -a ignore = ("test.xml");
+          echo "$ignore[*]"
           readarray -d , -t arr < .github/workflows/check_for.txt
+          echo "$arr[*]"
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do  
             fail_it="false"
             if [[ " ${ignore[*]} " =~ " ${file} " ]]; then
                 echo "$file is ignored"
             else
-              for i in "${arr[@]}"
-                do
-                  if grep -q $i "$file"; then
-                    echo "$file has $i fail it"
-                    fail_it="true"
+                for i in "${arr[@]}"
+                  do
+                    if grep -q $i "$file"; then
+                      echo "$file has $i fail it"
+                      fail_it="true"
+                    fi
+                  done
+                  if [ $fail_it == "true" ]; then
+                    exit 1
                   fi
-                done
-                if [ $fail_it == "true" ]; then
-                  exit 1
-                fi
             fi
           done
